---
- name: Get count
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      # if api_key vars are omitted, INTERSIGHT_API_KEY_ID, INTERSIGHT_API_PRIVATE_KEY,
      # and INTERSIGHT_API_URI environment variables used for API key data
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit) }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'INTERSIGHT_API_PRIVATE_KEY') }}"

    - name: Set filename
      ansible.builtin.debug:
        keyfile_name: "{{ lookup('env', 'INTERSIGHT_API_PRIVATE_KEY') }}"

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ lookup('file', keyfile_name) }}"

    # Get server data
    - name: Get all servers
      cisco.intersight.intersight_info:
        <<: *api_info
        server_names:
      register: servers
      no_log: false
      environment:
        ANSIBLE_DEBUG: 1

    - name: Print server count
      ansible.builtin.debug:
        msg: "Server count {{ servers.intersight_servers | length }}"
